name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: production
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: tokyopc.azyobuzi.net
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
